application: lotteline-shop
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /js
  static_dir: js
- url: /.*
  script: _go_app
